### ISSUE TITLE
Deprecate the use of `compoundVariant` keyword argument?

### ISSUE THREAD

**Issue by javierav** [avo-hq/class_variants#19]
@adrianthedev  Should we deprecate the use of `compoundVariant` keyword argument in favor of `compound_variant`? The first option does not comply with standard / community naming rules.

**Comment by adrianthedev** [comment]
Yes! Definitely! IDK what I was thinking at the time 🤦‍♂️

**Comment by javierav** [comment]
> Yes! Definitely! IDK what I was thinking at the time 🤦‍♂️

Neither do I, who was the one who did it! 🤦‍♂️🤦‍♂️ Implemented in #20

**Comment by adrianthedev** [comment]
Hahahha. It happens 😅
