### ISSUE TITLE
Compound Variants support

### ISSUE THREAD

**Issue by ErnestoR** [avo-hq/class_variants#4]
Thanks for releasing this library!

I was wondering if it was planned to have `compoundVariants` such as:

-  https://stitches.dev/docs/variants#compound-variants
- https://github.com/joe-bell/cva

**Comment by adrianthedev** [comment]
That's a nifty feature. Yeah, that would be cool to have.
Are you available to send in a PR?

**Comment by javierav** [comment]
@adrianthedev this issue can be closed as #8 is merged!
